version: '2'
services:
  spingularchatsql5-app:
    image: spingularchatsql5
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://spingularchatsql5-postgresql:5432/spingularchatsql5
      - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    ports:
      - 8080:8080
  spingularchatsql5-postgresql:
    extends:
      file: postgresql.yml
      service: spingularchatsql5-postgresql
